Fixing fatal: StandardIn has not been redirected. #1170
git-ecosystem/git-credential-manager pull request #1171
Opened 2023-03-28 08:54 UTC by ThePlenkov

Fix #1170

2023-03-28 08:56 UTC, ThePlenkov commented
Hi! I'm not a C# dev - so i'm not sure if it's a correct change. I just found that people advise to start the child process before writing to it.

2023-03-31 15:54 UTC, mjcheetham requested changes
Thanks for spotting this! The appears to be an oversight that occurred in [9fdda333](https://github.com/git-ecosystem/git-credential-manager/commit/9fdda3331a4a5de2df0a88aa1b981927bad5b3d5#diff-249f539d00b2ebf9d6c8455cddc8ff60c99714cdd03fbff602b01bed54f0fe9b) where we replaced a call to `Process.Start(psi)` to `_processManager.CreateProcess(psi)`, which doesn't automatically start the process.

You are correct that we should be looking to call `.Start()`, but we should also handle error condition of a failed start, and fix the same bug in the `DecryptFile` method.

2023-03-31 15:54 UTC, mjcheetham commented on src/shared/Core/Gpg.cs
> +
The `null` check above only made sense when we were calling `Process.Start(...)` which returns `null` when internally, the `Start()` call was `false`.

To maintain behaviour we should probably do this instead:

```csharp
if (!gpg.Start())
{
    throw new Trace2Exception(_trace2, "Failed to start gpg.");
}
```

We should also do the same thing to fix the bug that existing just a bit further up in the `DecryptFile()` method.

2023-04-04 16:48 UTC, mjcheetham commented
Closing in favour of #1177

2023-04-04 16:48 UTC, closed without merging