use universal Gitea OAuth configuration
git-ecosystem/git-credential-manager pull request #1442
Opened 2023-10-19 20:56 UTC by hickford

https://docs.gitea.com/next/development/oauth2-provider?_highlight=oauth#pre-configured-applications

Fixes #1426

2023-10-23 19:02 UTC, mjcheetham requested changes
Great to see Gitea has a universal app registration for GCM (and credential-oauth)!

Just two comments on structure/style of constants and case matching.

2023-10-23 19:02 UTC, mjcheetham commented on src/shared/Core/GenericOAuthConfig.cs
> +                config.RedirectUri = new Uri("http://127.0.0.1");
Could we move some of these string literals to constants, perhaps a static inner-class `WellKnownConfig` or something? I can imagine this set of config growing in the future.

```suggestion
                config.ClientId = WellKnown.GiteaClientId;
                authzEndpointUri = new Uri(remoteUri, WellKnown.GiteaAuthzEndpoint);
                tokenEndpointUri = new Uri(remoteUri, WellKnown.GiteaTokenEndpoint);
                config.RedirectUri = WellKnown.LocalIPv4RedirectUri;
```

```csharp
public static class GenericOAuthConfig
{
    ...

    public static class WellKnown
    {
        // https://docs.gitea.com/next/development/oauth2-provider?_highlight=oauth#pre-configured-applications
        public const string GiteaClientId = "e90ee53c-94e2-48ac-9358-a874fb9e0662";
        // https://docs.gitea.com/next/development/oauth2-provider?_highlight=oauth#endpoints
        public const string GiteaAuthzEndpoint = "/login/oauth/authorize";
        public const string GiteaTokenEndpoint = "/login/oauth/access_token";
        public static Uri LocalIPv4RedirectUri = new Uri("http://127.0.0.1");
    }
}
```

Can also reference these magic strings in the unit tests too.

`GenericOAuthConfig.WellKnown.*`

2023-10-23 19:02 UTC, mjcheetham commented on src/shared/Core.Tests/GenericOAuthConfigTests.cs
> +        public void GenericOAuthConfig_TryGet_Gitea()
Tests! ❤️

2023-10-24 17:19 UTC, ldennington approved these changes

2023-10-24 17:20 UTC, merged

2023-12-20 08:07 UTC, MissLov3ly reviewed
.

2023-12-20 15:14 UTC, Backuser617 commented
I need help

On Wed, Dec 20, 2023, 3:08 AM i.am_pi3 ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/git-ecosystem/git-credential-manager/pull/1442#pullrequestreview-1790368494>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BEZ44YJJTR2SN6M7275GUM3YKKMGJAVCNFSM6AAAAAA6H2M27OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJQGM3DQNBZGQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: <git-ecosystem/git-credential-manager/pull/1442/review/1790368494@
> github.com>
>