install-from-source: update libssl for alpine
git-ecosystem/git-credential-manager pull request #1574
Opened 2024-04-08 21:53 UTC by ldennington

The `validate-install-from-source` workflow is [currently failing](https://github.com/git-ecosystem/git-credential-manager/actions/runs/8604126129). According to [SO](https://stackoverflow.com/questions/77640298/dockerfile-unable-to-select-packages-linux-alpine) and [the .NET docs](https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine), the solution is to upgrade the `libssl` version from 1.1 to 3, as version 1.1 is out of support.

Verified with a test run [in my fork](https://github.com/ldennington/git-credential-manager).

2024-04-15 21:00 UTC, mjcheetham commented
This is the same PR as what @dscho did in https://github.com/git-ecosystem/git-credential-manager/pull/1535

The same issue occurs however in that we need to still use libssl1.1 for older versions of Alpine, so we need to update the script to switch on the Apline version.

2024-04-15 22:27 UTC, ldennington commented
> The same issue occurs however in that we need to still use libssl1.1 for older versions of Alpine, so we need to update the script to switch on the Alpine version.

Not quite sure if I picked up what you're putting down, but I added a check to make sure the user is running on 3.15 or greater. Will that suffice?

2024-04-16 01:09 UTC, mjcheetham requested changes
I'd like to propose this PR address this issue instead:
https://github.com/git-ecosystem/git-credential-manager/pull/1582

It copes with both 3.14 and 3.15+ Alpine requirements.

2024-04-16 02:24 UTC, ldennington commented
> Not quite sure if I picked up what you're putting down, but I added a check to make sure the user is running on 3.15 or greater. Will that suffice?

Actually, thinking about this a little more, it seemed like the best idea would be to set the version of `libssl` we use based on the version of Alpine the user is running. I've made updates accordingly and tested both scenarios (>3.14 and 3.14 and below) in my fork.

2024-04-16 02:37 UTC, ldennington commented
> I'd like to propose this PR address this issue instead:
> 
> https://github.com/git-ecosystem/git-credential-manager/pull/1582
> 
> 
> 
> It copes with both 3.14 and 3.15+ Alpine requirements.

Sorry! I didn't see this before submitting my updates. I'll take a look at your PR.

2024-04-16 15:28 UTC, closed without merging

2024-04-16 15:28 UTC, ldennington commented
Closed in favor of #1582